micronaut:
  application:
    name: exampleAtp
  executors:
    io:
      type: fixed
      nThreads: 75
datasources:
  default:
    url: jdbc:oracle:thin:@mnociatp_high?tnsAdmin=/tmp/wallet
    driverClassName: oracle.jdbc.OracleDriver
    username: mnocidemo
    password: MicronautDemo2021
    dialect: ORACLE
    data-source-properties:
      oracle:
        jdbc:
          fanEnabled: false
flyway:
  datasources:
    default:
      enabled: true          