micronaut:
  application:
    name: example-atp
  server:
    thread-selection: IO
  executors:
    io:
      type: fixed
      nThreads: 75
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
flyway:
  datasources:
    default:
      enabled: true          