micronaut:
  application:
    name: exampleAtp
  executors:
    io:
      type: fixed
      nThreads: 75
datasources:
  default:
    url: jdbc:oracle:thin:@mnociatp_high
    driverClassName: oracle.jdbc.OracleDriver
    username: mnocidemo
    password: ''
    dialect: ORACLE
    data-source-properties:
      oracle:
        jdbc:
          fanEnabled: false