micronaut:
  application:
    name: example-atp
  server:
    thread-selection: IO
  executors:
    io:
      type: fixed
      nThreads: 75
datasources:
  default:
    dialect: ORACLE
flyway:
  datasources:
    default:
      enabled: true          