CREATE TABLE "PET" ("ID" VARCHAR(36),"OWNER_ID" NUMBER(19) NOT NULL,"NAME" VARCHAR(255) NOT NULL,"TYPE" VARCHAR(255) NOT NULL);
CREATE TABLE "OWNER" ("ID" NUMBER GENERATED ALWAYS AS IDENTITY,"AGE" NUMBER(10) NOT NULL,"NAME" VARCHAR(255) NOT NULL);
